language: ruby
rvm:
  - 2.4.4
  - 2.5.1
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
before_script:
  - export WPXF_ENV=test
script:
  - bundle exec rspec
branches:
  except:
    - gh-pages
